###
# Site Meta
###

title: æ˜¥æ°´ç…èŒ¶
description: å±±ä¸­ä½•äº‹ï¼Ÿæ¾èŠ±é…¿é…’ï¼Œæ˜¥æ°´ç…èŒ¶ã€‚

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://writings.sh"

###
# Author
###

email: hit9@icloud.com
author_name: Chao Wang
author_name_cn: ç‹è¶…
author_location: ä¸Šæµ·
twitter_username: _hit9
github_username: hit9
douban_username: hit9
gravatar_link: https://s.gravatar.com/avatar/ea15c4cf155e86fc429d94a41ddbbcb6

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - venv
  - vendor
  - Makefile
  - gulpfile.js
  - package.json
  - package-lock.json
  - Caddyfile
  - sqip-images.sh
  - deploy.sh
  - fix-lazyload-in-feed.sh
  - fix-mathjax-in-feed.sh
  - assets/src

# Image
enable_post_image_render: true  # Post head large image
enable_image_lazyload: true  # Disable to load image directly.
image_prefix: "/assets/images/posts/"   # Ends with slash

copyright_declaration: 'æœªç»å…è®¸ï¼Œä¸å¾—è½¬è½½'
copyright_declaration_for_print: 'æºè‡ªåšå®¢ã€Œæ˜¥æ°´ç…èŒ¶ã€'

plugins:
  - jekyll-feed
  - jekyll-sitemap

disqus:
  enabled: false
  shortname: secret-garden-1

gitalk:
  enabled: true
  client_id: "b49909a7c3f92a0c9e3f"
  client_secret: "1f69d2d171d80104a32664c3d6817bdb7778c01e"
  repo: "writings-sh"
  owner: "hit9"
  admin: "hit9"

bymeacoffee:
  enabled: false

google_analytics_gtag:  "UA-145761297-1"

### feedburner

feedburner_url: https://feeds.feedburner.com/writings-sh

# Hire
hire:
  enabled: false
  hire_link: "https://zi.com/w/a/95274tw"
  hire_text: "ğŸ¦„ æˆ‘çš„å›¢é˜Ÿæ­£åœ¨å¯»ä¼˜ç§€çš„å°ä¼™ä¼´åŠ å…¥~ ï¼ï¼"
